### ISSUE TITLE
Story 1.1

### ISSUE THREAD

**Issue by OliMosby** [Hello-OST/easychat#2]
Als Chatbenutzer möchte ich eine strukturierte Webseite, damit ich eine schnelle Übersicht der
Applikation habe.

**Tasks**
- [ ] Angular Projekt erstellen
- [ ] HTML-Code editieren (Header, Footer, etc.)
- [ ] CSS-Code editieren (Design)

**Check List**
AK | &#10003;
--|--
AK1: Header (weiss @FFFFFF) mit schwarzer Trennlinie, Footer und Content Bereich (weiss) vorhanden
AK2: Aufteilung muss visuell ersichtlich sein
AK3: Footer ist grau #a0a0a0
AK4: Prod auf Chrome (latest)
AK5: Aufteilung Header:Content:Footer ist 1:3:1
