### ISSUE TITLE
Story 7.1

### ISSUE THREAD

**Issue by OliMosby** [Hello-OST/easychat#46]
Als User möchte ich, dass das UX Design optimiert wird damit EasyChat benutzerfreundlicher und auf die Zielgruppe ausgerichtet wird. Zu diesem Zweck wird eine UX Umfrage mit fünf qualitativen und fünf quantitativen Kriterien vorgenommen und das UX Design anhand der Auswertung dieser Umfrage überarbeitet. 

**Tasks**
- [x] Fragebogen für UX Umfrage erstellen
- [x] Mindest-Grenze bezüglich Erfüllbarkeitsgrad bei quantitativen Kriterien festlegen
- [x] Befragung mit mehreren Usern durchführen
- [x] Befragung auswerten: Qualitative Kriterien lesen und quantitative Kriterien bezüglich Mindest-Grenze Erfüllbarkeitsgrad überprüfen
- [x] Vom PO akzeptierte Inputs umsetzen

**Check List**
AK | &#10003;
--|--
AK1: Die Schrift bei disableden Buttons ist schwarz | &#10003;
AK2: Das Logo wird grösser dargestellt | &#10003;
